### PR TITLE
Login

### PR DESCRIPTION
**Pull request by Arnav-Bhardwaj**
We added the user restrictions and password restrictions and reviewed that issue #27 #13 are resolved, and thus completing User-Feature #11, for sprint 2.

### CODE REVIEW

**Comment by Songtone** [comment]
When I look at the site. The footer seems to be not attached to the bottom. Let's try to fix that. Other than that, when logging in you can clearly see the difference on the ad when one is posted. I think before I approve this, we should fix the footer issue! 
Good job tho!

**Comment by Arnav-Bhardwaj** [comment]
@Songtone , I agree with your comment but your suggestion would be more relevant for the issue #21, lets fix that in issue #21 and keep this separate from that issue. Thanks for letting me thou !

**Review by Songtone — APPROVED** [review]
It looks really good, The footer issue was fixed! We will obviously have more features that won't be shown when the user is not logged in but for what we have now it's really good!

**Comment by JKukulsky** [comment]
@mohghalayini don't forget to review this so we can merge it. The changes are small compared to other merges so it would be good to get this one in first.

**Review by mohghalayini — APPROVED** [review]
Features are okay but code is unorganized and has only a few comments. Good job on fixing the footer quickly though

**Comment by JKukulsky** [comment]
@Arnav-Bhardwaj feel okay with resolving the conflict and merging?

**Pull request merged**
