### PR TITLE
Modification of text on button

### PR DESCRIPTION
**Pull request by MBastiampillai**
As for now, the change is done for all users and does not occur for the user that licked the button itself. This will be corrected later on.

### CODE REVIEW

**Comment by Songtone** [comment]
I tried it out. The button stays there even after i clicked to like it, the button stays as yes. I am not sure what we want.

**Comment by JKukulsky** [comment]
HI @MBastiampillai. You'll need to add reviewers to this Pull request.

I went ahead and tested it locally on my machine, on a newly created card, the word "yes" appears where it used to say "like". Even when pressed it remains the same ("yes"). I'm guessing you're not finished? Typically a Pull Request is made when your branch is ready for review and integration.

**Comment by MBastiampillai** [comment]
yes sorry, the code is still a little bit buggy, it is yet to be finished . I will continue to work on it.

**Comment by SiamakSamie** [comment]
this needs to be resolved. Better to restart with lastest code from master

**Pull request closed without merging**
