### PR TITLE
Enhanced profile page

### PR DESCRIPTION
**Pull request by MBastiampillai**
This contains all the modifications done needed to solve issue #138. 
**_Final product:_**
23659871_1949147638636416_1336940745_o

### CODE REVIEW

**Review by JKukulsky — CHANGES_REQUESTED** [review]
The overall theme of this page fits with the rest of the Website, however, I have a small Improvement I would like to see implemented. I don't think customers would like the profile info to be displayed using a cursive font. It diminishes the readability of the information. My advice would be to style the font to match the cards better. Bold is good, italics not so much. Overall text size could be bigger as well.

screen shot 2017-11-15 at 3 22 13 pm

**Review by Songtone — APPROVED** [review]
The profile page looks like it fits well with the rest of the website. The code looks clean also.  Nice job!

**Review by MBastiampillai — COMMENTED** [review]
The changes requested concerning the font style and size were addressed and the code was modified to fit these requests.

**Review by Arnav-Bhardwaj — APPROVED** [review]
Great ! the font size and style is a huge improvement to the profile page. Good Job placing some comments to explain the Css code. Approved to merge

**Review by JKukulsky — APPROVED** [review]

**Pull request merged**
