### PR TITLE
Working on CSS

### PR DESCRIPTION
**Pull request by Songtone**
I am not finished but you guys can look at it and give me updates if you want. I made a lot of changes to the CSS but its hard to keep everything else intact. Let me know if you see any bugs.

need someone to make the time stamp nicer.

### CODE REVIEW

**Comment by Songtone** [comment]
I am still working on this, Don't merge it since I am not done yet. Here is a picture for everyone to see without having to open meteor.
image

**Comment by JKukulsky** [comment]
Overall, the look is getting better. I don't see a background, like the picture above. Colors logo and nav bar buttons (green) should be changed to match new colour scheme. Arrangement of test in the want cards should be better spaced, and text could be slightly enlarged. Good work.

screen shot 2017-10-30 at 1 59 15 pm

**Review by JKukulsky — COMMENTED** [review]
[Removed]

**Comment by JKukulsky** [comment]
Overall, the look is getting better. I don't see a background, like the picture above. Colors of logo and nav bar buttons (green) should be changed to match new colour scheme. Arrangement of text in the want cards should be better spaced, and text could be slightly enlarged. Good work.

screen shot 2017-10-30 at 1 59 15 pm

**Comment by Arnav-Bhardwaj** [comment]
Change the way cards appear as they don't fit with the background anymore. Overall I believe the background is neat.

**Comment by JKukulsky** [comment]
Also, subcategory is not being shown on new cards (as seen on the second card in my last screenshot).

**Comment by Arnav-Bhardwaj** [comment]
you could put search icon and also make the featured post text large with some reasonable space in between the text and the cards.

**Comment by Songtone** [comment]
This is an updated version.
image

**Comment by Songtone** [comment]
Made some more changes. Did a lot of changes to the cards, Need someone to change the date format.
Here is the most recent update.
image

**Comment by Songtone** [comment]
Here is an update.
image

**Comment by Songtone** [comment]
Having issue with the search. Will try to find the bug.

**Comment by Arnav-Bhardwaj** [comment]
great job @Songtone ! i believe we can close this issue since u did alot of commits for the sprint 4 and now so please review this @JKukulsky  @DJNGattuso  so we can merge this look into our repo.

**Review by JKukulsky — APPROVED** [review]
The new theme was well thought out. Great work.

**Review by DJNGattuso — APPROVED** [review]
Looks good! Great progress and effort!!

**Pull request merged**
