### PR TITLE
Dev/expand user input for profile card

### PR DESCRIPTION
**Pull request by Arnav-Bhardwaj**
Josh and I Added the information for the form along with storing into a collection "UserData" to store  the user information and display later in the #63

### CODE REVIEW

**Review by mohghalayini — APPROVED** [review]
there s no functionality yet and we don t know if it s the correct implementation or not .
Im waiting to see if thiis works but I approved cause it doesnt break the code

**Comment by Arnav-Bhardwaj** [comment]
@mohghalayini  There is functionality it stores the information in the collection userData, check with ctrl+m when you are on the website to mange the collection

**Review by DJNGattuso — CHANGES_REQUESTED** [review]
This looks good and seems that its working. We need to fix the way to check it though cause at the moment, it's hard to make sure that its performing properly.

I think the button to add profile data should be in the profile page. We don't need to do this switch in this issue as it isn't mentioned. But something that should be done eventually

I'll like you to add an explanation to why the meteor versions are changed before I approve

**Comment by JKukulsky** [comment]
@DJNGattuso I found that some of our package versions are more up-to-date in this branch than master. Once merged, the master will be updated.

**Review by DJNGattuso — APPROVED** [review]
Alright seems good now!

**Pull request merged**
