### PR TITLE
Finished the edit feature for posts

### PR DESCRIPTION
**Pull request by mohghalayini**
Created a button on each post that the user can click to edit his Want card weather it's sub category, category, description or title. 
I added the subcategory element to the cards just below the Main category.

this pull request should conclude issue #76.

### CODE REVIEW

**Comment by mohghalayini** [comment]
for further information about how I pulled out the information from the database please refer to the links below:
http://meteortips.com/first-meteor-tutorial/databases-part-1/

**Comment by JKukulsky** [comment]
@mohghalayini I resolved the small merge conflict on templates.html, however during local testing, the edit button is not responding, and a random empty card is present under the footer!

**Comment by mohghalayini** [comment]
This is weird since I do not have that problem
Maybe try reseting your mongo db data base?? Meteor reset should do it

**Review by Arnav-Bhardwaj — CHANGES_REQUESTED** [review]
I like the overall progress on the issue
I do suggest on the editpost templete in js file function "submited edit post" the if statement is fine but try to make variable with empty string rather then just comparing it with "" for each of your checks inside the if.
The rest of the template for edit post is well organized but please add some comments to explain the sections you made. Also add more comments on the js file changes preferably your "edit-Post': function" 
and submit-edited-post function, just briefly comment on what you tried to do with the jquery and how your if will allow edit to work. I can understand the code but others might not so it will be best practice to include comments as part of development 👍

**Comment by mohghalayini** [comment]
@Arnav-Bhardwaj  Comments have been added, hopefully they are enough

**Review by Arnav-Bhardwaj — APPROVED** [review]

**Review by MBastiampillai — APPROVED** [review]

**Pull request merged**
