### PR TITLE
User Profile Page

### PR DESCRIPTION
**Pull request by MBastiampillai**
Hey guys, this is the generic user profile page that I created. I didn't follow the color scheme or form of the previous web page since this page will be temporary and I will edit it later on. I've included the aspects of the username, profile picture as well as skills as requested. Can you guys review it and give me your opinion?
Thank you,
Mario Bastiampillai

### CODE REVIEW

**Review by mohghalayini — DISMISSED** [review]
good for now but it's too basic, I see a lot of more features that could be added to it.

**Review by JKukulsky — CHANGES_REQUESTED** [review]
@MBastiampillai . Content is basic but sufficient for sprint 2. Before any merge can take place, I would like to see the contents of the UserProfilePage.html profile page put into a container inside the client/main.html, placed under the "want" cards, but above the footer, just for now, until we know how to route. I put the profile contents on the main page locally quite easily in the html file, however the style code was non-integratable. Please use the css formatting that is used in the rest of the client to make the profile container look like the rest. I doesn't have to be perfect, but I would like to see the text to be the same font and size, common colours would be great too.

**Review by MBastiampillai — COMMENTED** [review]
attempting to use the css formatting of the rest of the client to make the profile page look similar, difficulties merging the two css codes. Will continue to work on it.

**Review by JKukulsky — APPROVED** [review]

**Review by DJNGattuso — APPROVED** [review]
Good job Mario! The template looks good. Let's work on getting it to a new page in sprint 3

**Pull request merged**
