### PR TITLE
User Data Collection and Retrieval for Profile Page

### PR DESCRIPTION
**Pull request by JKukulsky**
Retrieve and Display main user information on Profile Card #84
(Parent) As a user, I'd like to have a profile page to see my account information #46

Data fetched from users Collection: userId, userName, email
Data fetched from input filed: firstName, lastName, city, province, phoneNumber, picture.
All data stored in userData Collection.
All data retrieved from userData Collection for display on Profile Page.

**BUG: If the user completes the 'Fill Profile' form A SECOND TIME (to edit), the original profile card remains, and a second is placed below it. EDIT FUNCTIONALITY WILL BE ADDED IN SPRINT 5**

### CODE REVIEW

**Comment by JKukulsky** [comment]
Nice to see the team effort on this one!

**Review by Songtone — CHANGES_REQUESTED** [review]
There is an issue where my skills are already written for me. I have to click the submit button multiple times. I think we should add an edit button to the profile page. The bottom of the profile page is not doing anything from what I can see. Also, when registering for a new account, we don't ask the user to confirm their password. Otherwise everything else is good.

**Comment by JKukulsky** [comment]
@Songtone 
**Skills:** The skills are now input-able by the user.
**Submit Button:** That is a Meteor issue.
**Edit Button:** Will be moved to user page in Sprint 5.
**Password Confirmation:** Will be addressed in Sprint 5.

**READY FOR MERGE**

**Review by Songtone — APPROVED** [review]

**Comment by Songtone** [comment]
Everything that was said works. The other things will be addressed in sprint 5.

**Review by SiamakSamie — APPROVED** [review]
Good. I appreciate the cleaning up of some variable names in the main.js. You put the backend code in its own file called "profile.js". Thank you, our main.js was getting really messy. We should also seperate some other of the funtions in there into their own js files and then place all of them in a folder called "js".

**Pull request merged**
