### PR TITLE
Dev/search dropdown

### PR DESCRIPTION
**Pull request by DarrinFong**
Implementation of issue #135

- Please view issue for Acceptance Criteria.

### CODE REVIEW

**Review by Arnav-Bhardwaj — CHANGES_REQUESTED** [review]
Perfect addition to the  search bar, now users can be able to search on basis of the they type of category they desire.
One suggestion is that since code quality are introduced into the project you should add comments  for the function post.search .
Also please do not return a huge statement of code at the end and remove 3 returns just put one at the end of function for readability, so suggestion is to place them in one variable say "findResult"  then make one return with that variable and its appropriate holding value will be assigned based on the logic you used automatically.
The rest is perfectly fine and done really neatly, also add brief comment on html stating what you added on top

**Comment by DarrinFong** [comment]
@Arnav-Bhardwaj Changes have been added.

**Review by SiamakSamie — APPROVED** [review]
Tested. All works well. 
Code is clean and easy to understand.
Eventually we'll need to relocate some of these functions or rename main.js into posts.js.

**Review by Arnav-Bhardwaj — COMMENTED** [review]
Good job , you have successfully implemented the changes.

**Pull request merged**
