### PR TITLE
Setting up a test case

### PR DESCRIPTION
**Pull request by DJNGattuso**
Made a test folder to store the test cases
Made a test.js to contain the test program

laika didn't seem to be there, did another nmp -install laika

Currently: can't seem to run laika...can't check if a test actually works

### CODE REVIEW

**Comment by DJNGattuso** [comment]
i'm thinking of discussing with the TA tomorrow about how he would run a test or how to fix the issue with laika

**Comment by Arnav-Bhardwaj** [comment]
Good use of adding basic test cases, Organization of the folders can help us in the future sprints to place all test functions in the test.js

**Review by Arnav-Bhardwaj — APPROVED** [review]

**Review by JKukulsky — APPROVED** [review]
I like the test case folder to save test files. And the Js script for tests was great too

**Review by Arnav-Bhardwaj — COMMENTED** [review]
Good progress Like the fact we have a test folder setup done to store the js file which can be used later to test.
We have laika now to run js file and test from their automated testing later.

**Pull request merged**
