### PR TITLE
Small features

### PR DESCRIPTION
**Pull request by mohghalayini**
some bug fixing (like user not being able to delete nor edit his posts)
some new features ( user being able to edit and delete in his profile page ONLY)
some fixes( close button reworked in the editModal and addPost Modal

### CODE REVIEW

**Comment by mohghalayini** [comment]
this pull request closes issue #105 
is part of #150 
and will include #113

**Review by JKukulsky — APPROVED** [review]
Propper use of templating. CSS structure adhered to. These bug fixes came at a crucial stage in this project.

**Comment by mohghalayini** [comment]
#113 should be closed

**Review by Songtone — APPROVED** [review]
Very good bug fixes. The delete button and edit button works perfectly only in the profile page as expected.
Code is very clean.

**Pull request merged**
