### PR TITLE
Searching through DB as user types

### PR DESCRIPTION
**Pull request by SiamakSamie**
When user types any letter or number or backspace, the search bar returns search results on key-up. #74

### CODE REVIEW

**Review by DJNGattuso — APPROVED** [review]
For such a nice feature, it really has very little code lol
Its clean and its working well. 

Keep in mind to add some comments to explain what's going on or what should happen

**Comment by JKukulsky** [comment]
Added the Ad category to be searchable as well. Very nice feature in general.

**Comment by JKukulsky** [comment]
Good observations Darrin, we should revert these changes.

**Comment by SiamakSamie** [comment]
I think server load is negligeable. The Instant Search feature is more modern and appealing to users.

**Review by DarrinFong — CHANGES_REQUESTED** [review]
Sorting by likes has been removed, review code and run app before pushing.

**Comment by DJNGattuso** [comment]
Be careful, the commit says "marge branch "master" into searchBarFeature"

I don't think you'd want to do that, I believe you meant to merge the opposit. 

Take a look and fix it before doing the merge whenever that may be

**Comment by DarrinFong** [comment]
@DJNGattuso Merging master into dev branch will update dev branch, this prevents outdated code from overwriting current code. It's good practice.

**Comment by DJNGattuso** [comment]
Oh cool, never knew! Thanks

**Pull request closed without merging**
